/*
MySQL Data Transfer
Source Host: localhost
Source Database: lineage
Target Host: localhost
Target Database: lineage
Date: 2013/12/2 13:26:49
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for definite_scroll
-- ----------------------------
CREATE TABLE `definite_scroll` (
  `nameid` varchar(50) NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `msgid` int(11) DEFAULT '0',
  `type` enum('Weapon','Armor','Food','Have','Etc') NOT NULL,
  PRIMARY KEY (`nameid`),
  KEY `item_nameid` (`nameid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='鉴定卷轴';

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `definite_scroll` VALUES ('$167', '皮夾克', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1031', '皮背心', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$798', '木製的夾克', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$116', '小藤甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$165', '歐西斯環甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1033', '銀釘皮背心', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$580', '綿質長袍', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$163', '銀釘皮甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$164', '環甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1032', '皮盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1034', '硬皮背心', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$781', '木甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1207', '法師長袍', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$162', '鱗甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$160', '歐西斯鏈甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$782', '精靈護胸金屬板', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$159', '鏈甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$516', '抗魔法鏈甲', '167', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$595', '精靈鏈甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1035', '骷髏盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$788', '精靈金屬盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$155', '藤甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$156', '皮甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$154', '青銅盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$152', '金屬盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1212', '鋼鐵金屬盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$153', '水晶盔甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$142', '青龍鱗甲', '404', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$137', '赤龍鱗甲', '405', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$141', '藍龍鱗甲', '403', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$138', '白龍鱗甲', '406', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$186', '小盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$191', '歐西斯盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$189', '阿克海盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$778', '木盾', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1028', '皮盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$187', '精靈盾牌', '114', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$193', '大盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$194', '侏儒圓盾', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$196', '反射之盾', '119', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$922', '銀騎士之盾', '289', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1029', '銀釘皮盾', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$429', '塔盾', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1030', '骷髏盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1210', '鋼鐵盾牌', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$419', '伊娃之盾', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$172', '歐西斯斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$174', '侏儒斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$170', '精靈斗篷', '105', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$180', '隱身斗篷', '110', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$182', '抗魔法斗篷', '111', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$312', '紅騎士之斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$176', '油布斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$184', '位移斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$178', '保護者斗篷', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$330', '手套', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$775', '腕甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$795', '力量手套', '280', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1799', '가죽장갑', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1208', '鋼鐵手套', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$119', '皮帽', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$128', '鋼盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$120', '歐西斯頭盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$118', '精靈皮盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1008', '夜視頭盔', '304', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$939', '敏捷魔法頭盔', '292', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$940', '力量魔法頭盔', '293', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1023', '皮頭盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$122', '侏儒鐵盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$569', '抗魔法頭盔', '229', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$790', '艾爾穆的祝福', '275', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1022', '銀釘皮帽', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1206', '法師之帽', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$414', '騎士面甲', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$413', '王冠', '139', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1024', '骷髏頭盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1209', '鋼鐵頭盔', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1027', '皮長靴', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1025', '皮涼鞋', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1211', '鋼鐵長靴', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$329', '長靴', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1026', '銀釘皮涼鞋', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$206', '短統靴', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$168', 'T恤', '104', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$828', '沙哈的護身符', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$241', '傳送控制戒指', '64', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$261', '變形控制戒指', '65', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$431', '沙哈的戒指', '0', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1013', '妖魔戰士護身符', '314', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$797', '都佩傑諾的項鍊', '282', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1007', '魅力項鍊', '311', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1006', '精神項鍊', '310', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1005', '智力項鍊', '309', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1004', '體質項鍊', '308', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1002', '力量項鍊', '306', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$1003', '敏捷項鍊', '307', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$938', '治癒魔法頭盔', '291', 'Armor');
INSERT INTO `definite_scroll` VALUES ('$4', '金幣', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$2', '燈', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$326', '燈籠', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$327', '燈油', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$67', '蠟燭', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$258', '創造怪物魔杖', '19', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$262', '閃電魔杖', '21', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$260', '變形魔杖', '20', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$328', '終級治癒藥水', '130', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$255', '強力治癒藥水', '15', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1253', '濃縮終極體力恢復劑', '804', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1252', '濃縮強力體力恢復劑', '803', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1251', '濃縮體力恢復劑 ', '802', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$242', '失明藥水', '16', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$507', '回覆魔力藥水', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$233', '翡翠藥水', '126', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$264', '自我加速藥水', '16', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1507', '伊娃的祝福', '417', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$943', '勇敢藥水', '296', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1508', '人魚之鱗', '418', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$944', '慎重藥水', '297', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$26', '治癒藥水', '14', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$110', '精靈餅乾', '86', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$799 $512', '고급 다이아몬드', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$799 $513', '고급 루비', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$799 $514', '고급 사파이어', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$799 $515', '고급 에메랄드', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$512', '鑽石', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$513', '紅寶石', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$514', '藍寶石', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$515', '綠寶石', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$800 $512', '최고급 다이아몬드', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$800 $513', '최고급 루비', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$800 $514', '최고급 사파이어', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$800 $515', '최고급 에메랄드', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$23', '肉', '10', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$6 $23', '괴물눈 고기', '9', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$72', '蛋', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$68', '胡蘿蔔', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$82', '檸檬', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$107', '香蕉', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$106', '蘋果', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1179', '情人禮物(糖果)', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$85', '橘子', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$249', '對盔甲施法的卷軸', '26', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$254', '毀滅盔甲的卷軸', '27', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$505', '傳送回家的卷軸', '162', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3304', '글루딘 마을 귀환서', '1345', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3310', '기란 마을 귀환 주문서', '1351', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1411', '指定傳送卷軸(歌唱之島)', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3303', '말하는 섬 마을 귀환 주문서', '1344', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$618', '全體傳送術的卷軸', '238', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$244', '對武器施法的卷軸', '25', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$971', '變形卷軸', '299', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$257', '復活卷軸', '28', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$230', '瞬間移動卷軸', '23', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1424', '指定傳送卷軸(隱藏之谷)', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3314', '아덴 마을 귀환 주문서', '1355', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3308', '요정숲 귀환 주문서', '1349', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3306', '우드벡 마을 귀환 주문서', '1347', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3313', '웰던 마을 귀환 주문서', '1354', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3309', '은기사 마을 귀환 주문서', '1350', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$243', '解除咀咒的卷軸', '24', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$228 $249', '저주받은 갑옷 마법 주문서', '26', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$228 $244', '저주받은 무기 마법 주문서', '25', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $249', '축복받은 갑옷 마법 주문서', '26', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $244', '축복받은 무기 마법 주문서', '25', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $971', '축복받은 변신 주문서', '299', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $257', '축복받은 부활 주문서', '28', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $230', '축복받은 순간이동 주문서', '23', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$227 $243', '축복받은 저주 풀기 주문서', '24', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3305', '켄트 마을 귀환 주문서', '1346', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3311', '하이네 마을 귀환 주문서', '1352', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$3307', '화전민 마을 귀환 주문서', '1348', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$55', '鑑定卷軸', '22', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$501', '甘地圖騰', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$500', '那魯加圖騰', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$498', '都達瑪拉妖魔', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$502', '羅孚圖騰', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$499', '阿吐巴圖騰', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1654 $1616', '3연발 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1655 $1616', '6연발 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1668 $1654 $1616', '고급 3연발 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1627 $1630 $1616', '남색 2단 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1627 $1656 ', '남색 스파크', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1627 $1616', '남색 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1627 $1631 $1616', '남색 하트 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1625 $1630 $1616', '적색 2단 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1625 $1656', '적색 스파크', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1625 $1616', '적색 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1625 $1631 $1616', '적색 하트폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1630 $1629 $1616', '청색 2단 원형 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1630 $1616', '청색 2단 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1632 $1616', '청색 눈꽃폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1656', '청색 스파크', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1629 $1616', '청색 원형폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1616', '청색 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1626 $1631 $1616', '청색 하트폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$2683', '크리스마스 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1630 $1656 $1616', '황색 2단 원형폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1630 $1616 ', '황색 2단 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1632 $1616', '황색 눈꽃폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1656', '황색 스파크', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1629 $1616', '황색 원형폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1616', '황색 폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1628 $1631 $1616', '황색 하트폭죽', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$314', '往古魯丁的船票', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$307', '黃金鑰匙', '52', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1247', '賽狗場競賽票', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$315', '往說話之島的船票', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1100', '磨刀石', '348', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$954', '旅館鑰匙', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$308', '銀鑰匙', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1103', '地圖:古魯丁', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1102', '地圖:說話之島', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1104', '地圖:肯特城', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1105', '地圖:妖魔城堡', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1106', '地圖:妖精森林', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1107', '地圖:風木之城', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1108', '地圖:銀騎士村莊', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1109', '地圖:龍之谷', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1188', '地圖:奇岩', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1533', '地圖:歌唱之島', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1534', '地圖:隱藏之谷', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1535', '地圖:海音', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1607', '지도 웰던', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1086', '哨子', '343', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1075', '信紙', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1039', '高級皮革', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1036', '皮革', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1199', '紅色布料', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$149', '藍龍鱗', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1608', '아시타지오의 재', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$150', '青龍鱗', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1037', '金屬塊', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1197', '藍色布料', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$146', '白龍鱗', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1200', '白色布料', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$145', '赤龍鱗', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$508', '魔法寶石', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$777', '魔法笛子', '262', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$767', '純粹的米索莉塊', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$772', '米索莉線', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$761', '粗糙的米索莉塊', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$779', '米索莉金屬板', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$764', '蘑菇汁', '249', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$766', '線', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$769', '芮克妮的網', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$774', '芮克妮的蛻皮', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$770', '安特之樹皮', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$794', '安特的水果', '279', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$763', '安特之樹枝', '248', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$771', '奧里哈魯根', '256', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$780', '奧里哈魯根金屬板', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$765', '食人巨魔的血', '250', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$762', '元素石', '841', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$760', '潘的鬃毛', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$768', '精靈粉末', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$776', '精靈羽翼', '261', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1914', '간디 오크 마법서', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1040', '骨頭碎片', '0', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$1173', '項圈', '361', 'Etc');
INSERT INTO `definite_scroll` VALUES ('$13', '歐西斯匕首', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$416', '骰子匕首', '142', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$785', '短劍的劍身', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$70', '匕首', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$12', '精靈匕首', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$786', '長劍的劍身', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$787', '奧里哈魯根的劍身', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$99', '歐西斯短劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$793', '鎖子甲破壞者', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$66', '闊矛', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$100', '短劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1148', '銀劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$97', '小侏儒短劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$92', '彎刀', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$98', '精靈短劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1147', '銀長劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$313', '紅騎士之劍', '123', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$415', '侵略者之劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$598', '大馬士革刀', '235', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$16', '武士刀', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$789', '細劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$3', '雙手劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$17', '日本劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1048', '巨劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1020', '屠龍劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$783', '潘的角', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$791', '覆上米索莉的角', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$62', '巴迪須', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$96', '歐西斯之矛', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$63', '柴刀', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$102', '三叉戟', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$87', '帕提森', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$81', '槍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$25', '矛', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$76', '吉薩', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$75', '闊劍', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$95', '精靈之矛', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$792', '覆上奧里哈魯根的角', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$83', '露西錘', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$77', '戟', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$73', '法丘', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$71', '貝卡合金', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$572', '巫術魔法杖', '232', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1063', '瑪那魔杖', '342', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$570', '橡木魔法杖', '230', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$571', '美基魔法杖', '231', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$573', '力量魔法杖', '233', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1', '斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$14', '亞連', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$69', '木棒', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$74', '弗萊爾', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$20', '釘錘', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$111', '戰錘', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1149', '銀斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$60', '戰斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$94', '侏儒鐵斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$418', '狂戰士斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$84', '流星錘', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$412', '巨斧', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1244', '獵人之弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$64', '精靈弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$65', '歐西斯弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$24', '弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$759', '短弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$784', '十字弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$105', '尤米弓', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$61', '箭', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$93', '銀箭', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$773', '米索莉箭', '0', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$803', '魔法精靈短劍', '286', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$1098', '體質精靈短劍', '346', 'Weapon');
INSERT INTO `definite_scroll` VALUES ('$802', '敏捷精靈短劍', '347', 'Weapon');
