-- ----------------------------
-- Table structure for `etc_items`
-- 已廢棄：已合併至 items 表，可隨時刪除。ItemTable 僅讀取 items。
-- ----------------------------
DROP TABLE IF EXISTS `etc_items`;
CREATE TABLE `etc_items` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `unidentified_name_id` varchar(255) NOT NULL,
  `identified_name_id` varchar(255) NOT NULL,
  `item_type` varchar(255) NOT NULL,
  `use_type` varchar(255) NOT NULL,
  `effect_id` int(10) unsigned NOT NULL DEFAULT '0',
  `use_royal` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_knight` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_wizard` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_elf` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `add_str` tinyint(3) NOT NULL DEFAULT '0',
  `add_dex` tinyint(3) NOT NULL DEFAULT '0',
  `add_con` tinyint(3) NOT NULL DEFAULT '0',
  `add_int` tinyint(3) NOT NULL DEFAULT '0',
  `add_wis` tinyint(3) NOT NULL DEFAULT '0',
  `add_sp` tinyint(3) NOT NULL DEFAULT '0',
  `add_hit` tinyint(3) NOT NULL DEFAULT '0',
  `add_dmg` tinyint(3) NOT NULL DEFAULT '0',
  `add_bow_hit` tinyint(3) NOT NULL DEFAULT '0',
  `add_bow_dmg` tinyint(3) NOT NULL DEFAULT '0',
  `add_hp` int(10) NOT NULL DEFAULT '0',
  `add_mp` int(10) NOT NULL DEFAULT '0',
  `add_hpr` int(10) NOT NULL DEFAULT '0',
  `add_mpr` int(10) NOT NULL DEFAULT '0',
  `add_mr` tinyint(3) NOT NULL DEFAULT '0',
  `material` varchar(255) NOT NULL,
  `weight` int(10) unsigned NOT NULL DEFAULT '0',
  `inv_gfx_id` int(10) unsigned NOT NULL,
  `grd_gfx_id` int(10) unsigned NOT NULL,
  `item_desc_id` int(10) unsigned NOT NULL DEFAULT '0',
  `stackable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `max_charge_count` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `dmg_small` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `dmg_large` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `min_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `max_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `loc_x` int(10) unsigned NOT NULL DEFAULT '0',
  `loc_y` int(10) unsigned NOT NULL DEFAULT '0',
  `map_id` int(10) unsigned NOT NULL DEFAULT '0',
  `bless` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `tradable` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `deletable` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sealable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `delay_id` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `delay_time` int(10) unsigned NOT NULL DEFAULT '0',
  `delay_effect` int(10) unsigned NOT NULL DEFAULT '0',
  `food_volume` int(10) unsigned NOT NULL DEFAULT '0',
  `save_at_once` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `charge_time` int(10) unsigned NOT NULL DEFAULT '0',
  `expiration_time` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
