-- =============================================
-- 修復 skills 表：182 版 50 個魔法 + NPC/精靈魔法
-- ID 使用 JP 標準：(skill_level-1)*8 + skill_number + 1
-- 
-- 公式：JP_ID = (skill_level - 1) * 8 + skill_number + 1
-- 例：Lv2 No0 (解毒術) → (2-1)*8 + 0 + 1 = 9
-- =============================================

-- ============================================
-- 第一步：修復 character_skills 表中的舊 182 ID
-- 必須在 TRUNCATE skills 之前執行
-- 使用 CASE/WHEN 原子更新，避免級聯衝突
-- （例：182 ID 9→JP 12，但 182 ID 12 也存在）
-- ============================================
UPDATE character_skills
SET skill_id = CASE skill_id
    -- Lv2: 182 ID 6-10 → JP ID 9-13
    WHEN 6  THEN 9
    WHEN 7  THEN 10
    WHEN 8  THEN 11
    WHEN 9  THEN 12
    WHEN 10 THEN 13
    -- Lv3: 182 ID 11-15 → JP ID 17-21
    WHEN 11 THEN 17
    WHEN 12 THEN 18
    WHEN 13 THEN 19
    WHEN 14 THEN 20
    WHEN 15 THEN 21
    -- Lv4: 182 ID 16-20 → JP ID 25-29
    WHEN 16 THEN 25
    WHEN 17 THEN 26
    WHEN 18 THEN 27
    WHEN 19 THEN 28
    WHEN 20 THEN 29
    -- Lv5: 182 ID 21-25 → JP ID 33-37
    WHEN 21 THEN 33
    WHEN 22 THEN 34
    WHEN 23 THEN 35
    WHEN 24 THEN 36
    WHEN 25 THEN 37
    -- Lv6: 182 ID 26-30 → JP ID 41-45
    WHEN 26 THEN 41
    WHEN 27 THEN 42
    WHEN 28 THEN 43
    WHEN 29 THEN 44
    WHEN 30 THEN 45
    -- Lv7: 182 ID 31-35 → JP ID 49-53
    WHEN 31 THEN 49
    WHEN 32 THEN 50
    WHEN 33 THEN 51
    WHEN 34 THEN 52
    WHEN 35 THEN 53
    -- Lv8: 182 ID 36-40 → JP ID 57-61
    WHEN 36 THEN 57
    WHEN 37 THEN 58
    WHEN 38 THEN 59
    WHEN 39 THEN 60
    WHEN 40 THEN 61
    -- Lv9: 182 ID 41-45 → JP ID 65-69
    WHEN 41 THEN 65
    WHEN 42 THEN 66
    WHEN 43 THEN 67
    WHEN 44 THEN 68
    WHEN 45 THEN 69
    -- Lv10: 182 ID 46-50 → JP ID 73-77
    WHEN 46 THEN 73
    WHEN 47 THEN 74
    WHEN 48 THEN 75
    WHEN 49 THEN 76
    WHEN 50 THEN 77
    ELSE skill_id
END
WHERE skill_id BETWEEN 6 AND 50;

-- ============================================
-- 第二步：清空並重建 skills 表
-- ============================================
TRUNCATE TABLE skills;

-- 插入修正後的魔法數據
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1','初級治癒術','1','0','4','0','0','0','0','0','buff','0','4.0','10','1','0','0','-1','0','2','0','0','0','0','1','$1436','0','744','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('2','日光術','1','1','4','0','0','0','0','1800','none','0','1.0','13','1','0','0','-1','0','128','0','0','0','0','2','$1437','0','2510','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('3','保護罩','1','2','3','5','0','0','0','1800','none','0','1.0','0','0','0','0','-1','0','128','0','0','0','0','4','$1438','0','221','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('4','光箭','1','3','3','0','0','0','0','0','attack','0','1.0','1','1','0','0','-1','0','64','0','0','0','0','8','$1439','0','167','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('5','指定傳送','1','4','5','0','0','0','0','0','none','0','1.0','1','1','0','0','-1','0','128','0','0','0','0','16','$1440','0','169','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('9','解毒術','2','0','8','0','0','0','0','0','buff','0','2.0','1','1','0','0','-1','0','2','0','0','0','0','1','$1441','0','871','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('10','寒冷戰慄','2','1','9','1','0','0','0','0','attack','0','2.0','1','1','0','0','-1','0','64','2','0','0','0','2','$1442','0','252','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('11','毒咒','2','2','10','10','0','0','0','30','buff','0','2.0','1','1','0','0','-1','0','2','50','0','0','0','4','$1443','0','745','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('12','擬似魔法武器','2','3','15','0','0','0','0','1800','item','0','2.0','1','1','0','0','-1','0','128','0','0','0','0','8','$1444','0','747','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('13','無所遁形術','2','4','8','0','0','0','0','0','none','0','2.0','1','1','0','0','-1','0','128','0','12','0','0','16','$1445','0','749','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('17','極光雷電','3','0','14','3','0','0','0','0','attack','0','3.0','1','1','0','0','-1','0','64','0','2','0','0','1','$1446','0','170','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('18','起死回生術','3','1','15','0','0','0','0','0','buff','0','3.0','1','1','0','0','-1','0','2','0','0','0','0','2','$1970','0','754','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('19','中級治癒術','3','2','13','0','0','0','0','0','buff','0','24.0','20','1','0','0','-1','0','2','0','0','0','0','4','$1448','0','829','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('20','闇盲咒術','3','3','17','5','0','0','0','30','buff','0','3.0','1','1','0','0','-1','0','2','80','0','0','0','8','$1449','0','746','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('21','鎧甲護持','3','4','20','0','0','0','0','1800','item','0','3.0','0','0','0','0','-1','0','128','0','0','0','0','16','$1450','0','748','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('25','燃燒的火球','4','0','18','0','0','0','0','0','attack','0','4.0','1','1','0','0','-1','0','64','0','2','0','0','1','$1451','0','171','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('26','通暢氣脈術','4','1','23','0','0','0','0','1200','buff','0','4.0','1','1','0','0','-1','0','2','0','0','0','0','2','$1452','0','750','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('27','壞物術','4','2','26','20','508','1','0','0','buff','0','4.0','1','1','0','0','-1','0','2','200','0','0','0','4','$1453','0','172','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('28','吸血鬼之吻','4','3','15','1','0','0','0','0','attack','0','4.0','1','1','0','0','-1','0','64','1','0','0','0','8','$1454','0','236','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('29','緩速術','4','4','15','10','508','1','0','64','buff','0','4.0','1','1','0','0','-1','0','2','0','0','0','0','16','$1455','0','752','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('33','木乃伊的詛咒','5','0','35','30','508','2','0','30','buff','0','5.0','1','1','0','0','-1','0','2','0','0','0','0','1','$1456','0','746','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('34','極道落雷','5','1','23','0','0','0','0','0','attack','0','5.0','1','1','0','0','-1','0','64','0','0','0','0','2','$1457','0','10','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('35','高級治癒術','5','2','20','0','0','0','0','0','buff','0','68.0','30','1','0','0','-1','0','2','0','0','0','0','4','$1458','0','830','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('36','迷魅術','5','3','30','20','508','2','0','3600','buff','0','5.0','1','1','0','0','-1','0','2','0','0','0','0','8','$1459','0','228','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('37','聖潔之光','5','4','20','0','0','0','0','0','buff','0','5.0','1','1','0','0','-1','0','2','0','0','0','0','16','$1460','0','227','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('41','造屍術','6','0','35','20','508','2','0','3600','buff','0','6.0','1','1','0','0','-1','0','2','0','0','0','0','1','$1461','0','231','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('42','體魄強健術','6','1','25','15','0','0','0','1200','buff','0','4.0','1','1','0','0','-1','0','2','0','0','0','0','2','$1462','0','751','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('43','加速術','6','2','25','20','0','0','0','1200','buff','0','6.0','1','1','0','0','-1','0','2','0','0','0','0','4','$1463','0','755','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('44','魔法相消術','6','3','35','15','508','2','0','0','buff','0','6.0','1','1','0','0','-1','0','2','0','0','0','0','8','$1464','0','232','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('45','地裂術','6','4','20','15','0','0','0','0','attack','0','6.0','1','1','0','0','-1','0','64','0','0','0','0','16','$1465','0','129','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('49','體力回復術','7','0','40','60','0','0','0','0','none','0','68.0','30','1','0','0','-1','0','128','0','10','0','0','1','$1466','0','759','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('50','冰矛圍籬','7','1','35','8','0','0','0','20','attack','0','7.0','1','1','0','0','-1','0','64','0','0','0','0','2','$1467','0','756','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('51','召喚術','7','2','50','30','508','3','0','3600','none','0','7.0','1','1','0','0','-1','0','128','10','0','0','0','4','$1468','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('52','神聖的圓','7','3','45','10','0','0','0','32','none','0','7.0','1','1','0','0','-1','0','128','0','0','0','0','8','$1457','0','761','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('53','龍捲風','7','4','40','20','0','0','0','0','none','0','7.0','1','1','0','0','-1','0','128','0','4','0','0','16','$1470','0','758','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('57','全部治癒術','8','0','48','0','0','0','0','0','buff','0','138.0','30','1','0','0','-1','0','2','0','0','0','0','1','$1471','0','831','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('58','火牢','8','1','50','20','0','0','0','10','buff','0','8.0','1','1','0','0','-1','0','2','0','0','0','0','2','$1472','0','168','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('59','冰雪暴','8','2','60','10','0','0','0','0','none','0','8.0','1','1','0','0','-1','0','128','10','10','0','0','4','$1473','0','757','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('60','隱身術','8','3','60','60','0','0','0','1200','none','0','8.0','1','1','0','0','-1','0','128','0','0','0','0','8','$1474','0','147','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('61','返生術','8','4','50','0','0','0','0','0','buff','0','8.0','1','1','0','0','-1','0','2','0','0','0','0','16','$1475','0','3944','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('65','力場','9','0','60','20','0','0','0','0','attack','0','9.0','1','1','0','0','-1','0','64','0','4','0','0','1','$1461','0','3924','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('66','沉睡之霧','9','1','60','35','0','0','0','32','buff','0','9.0','1','1','0','0','-1','0','2','0','3','0','0','2','$1477','0','760','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('67','變形術','9','2','60','30','0','0','0','1000','buff','0','9.0','1','1','0','0','-1','0','2','0','0','0','0','4','$1478','0','231','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('68','聖結界','9','3','30','0','0','0','0','32','buff','0','9.0','1','1','0','0','-1','0','2','0','0','0','0','8','$1479','0','228','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('69','集體傳送術','9','4','100','20','0','0','0','0','none','0','9.0','1','1','0','0','-1','0','128','0','10','0','0','16','$1480','0','2236','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('73','創造魔法武器','10','0','200','100','508','10','0','0','item','0','10.0','1','1','0','0','-1','0','128','0','0','0','0','1','$1481','0','763','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('74','流星雨','10','1','70','0','0','0','0','0','attack','0','10.0','2','1','0','0','-1','0','64','0','2','0','0','2','$1482','0','762','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('75','反射之池','10','2','100','200','508','3','0','0','buff','0','10.0','1','1','0','0','-1','0','2','0','0','0','0','4','$1985','0','233','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('76','瞬間停止','10','3','80','50','508','5','0','3840','buff','0','10.0','1','1','0','0','-1','0','2','0','3','0','0','8','$1466','0','3932','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('77','究極光裂術','10','4','70','10','0','0','100','0','attack','0','10.0','5','1','0','0','-1','0','64','0','0','0','0','16','$1485','0','1815','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('129','魔法防御','17','0','5','0','1822','1','100','3600','none','0','0.0','0','0','0','0','-1','0','128','0','0','0','0','1','魔法防御','0','2186','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('130','心灵转换','17','1','0','5','0','0','400','0','none','0','1.0','0','0','0','0','-1','0','128','0','0','0','0','2','心灵转换','0','2179','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('131','世界树的呼唤','17','2','5','0','0','0','100','0','none','0','0.0','0','0','0','0','-1','0','128','0','0','0','0','4','世界树的呼唤','0','169','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('132',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('133',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('134',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('135',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('136',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('137','净化精神','18','0','15','0','0','0','0','1800','none','0','0.0','5','1','0','0','-1','0','128','0','0','0','0','1','净化精神','0','2180','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('138','属性防御','18','1','10','0','0','0','0','3600','none','0','0.0','10','1','0','0','-1','0','128','0','0','0','0','2','属性防御','0','2184','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('139',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('140',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('141',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('142',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('143',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('144',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('145',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('146','魂体转换','19','1','0','50','0','0','1200','0','none','0','0.0','0','0','0','0','-1','0','128','0','0','0','0','2','魂体转换','0','2178','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('147',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('148','火焰武器','19','3','10','0','0','0','0','600','buff','0','0.0','0','0','0','0','-1','2','2','0','0','0','0','8','火焰武器','0','2182','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('149','风之神射','19','4','20','0','0','0','0','600','buff','0','0.0','0','0','0','0','-1','8','2','0','0','0','0','16','风之神射','0','2246','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('150',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('151','大地防护','19','6','10','0','0','0','0','3600','buff','0','0.0','6','1','0','0','-1','1','2','0','0','0','0','64','大地防护','0','2249','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('152',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('153',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('154',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('155',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('156',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('157',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('158',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('159',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('160',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('161',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('162',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('163',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('164',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('165',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('166',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('167',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('168',NULL,'0','0','0','0','0','0','0','0',NULL,'0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0',NULL,'0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1000','克特:地獄火','0','0','30','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','2','0','0','0','克特:地獄火','0','1812','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1001','死亡骑士:地獄火','0','0','30','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','2','0','0','0','死亡骑士:地獄火','0','245','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1002','伊弗利特-火矛','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','8','0','0','0','伊弗利特-火矛','0','1776','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1003','不死鸟-火焰雨','0','0','5','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','6','0','0','0','不死鸟-火焰雨','0','1793','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1004','不死鸟-熔炎弹','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','8','0','0','0','不死鸟-熔炎弹','0','1794','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1005','巴拉卡斯-火焰喷吐','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','3','0','0','0','巴拉卡斯-火焰喷吐','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1006','巴拉卡斯-流星雨','0','0','5','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','25','0','0','0','巴拉卡斯-流星雨','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1007','法利昂-寒冰喷吐','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','3','0','0','0','法利昂-寒冰喷吐','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1008','法利昂-水压','0','0','5','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','25','0','0','0','法利昂-水压','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1009','安塔瑞斯-剧毒喷吐','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','3','0','0','0','安塔瑞斯-剧毒喷吐','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1010','安塔瑞斯-大地怒吼','0','0','5','0','0','0','0','0','none','0','5.0','5','1','0','0','-1','0','128','0','25','0','0','0','安塔瑞斯-大地怒吼','0','0','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1011','思克巴-妖女之吻','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','5','0','0','0','思克巴-妖女之吻','0','1115','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1012','思克巴女皇-妖女之吻','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','5','0','0','0','思克巴女皇-妖女之吻','0','1119','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1013','烈炎兽吐火攻击','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','2','0','0','0','烈炎兽吐火攻击','0','1783','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1014','加速术-怪物专用','0','0','5','0','0','0','0','1200','buff','0','5.0','5','1','0','0','-1','0','2','0','12','0','0','0','加速术-怪物专用','0','755','-1','0','0','0','0','0','1',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1015','地狱犬-喷火','0','0','5','0','0','0','0','0','attack','0','5.0','5','1','0','0','-1','0','64','0','2','0','0','0','地狱犬-喷火','0','954','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('1016','亚力安-冰矛围篱','0','0','5','0','0','0','0','20','attack','0','5.0','5','1','0','0','-1','0','64','0','0','0','0','0','亚力安-冰矛围篱','0','2510','-1','0','0','0','0','0','0',NULL);
INSERT INTO `skills` (`id`,`name`,`skill_level`,`skill_number`,`consume_mp`,`consume_hp`,`consume_item_id`,`consume_amount`,`reuse_delay`,`buff_duration`,`target`,`target_to`,`damage_value`,`damage_dice`,`damage_dice_count`,`probability_value`,`probability_dice`,`probability_max`,`attr`,`type`,`lawful`,`ranged`,`area`,`through`,`skill_id`,`name_id`,`action_id`,`cast_gfx`,`cast_gfx2`,`sys_msg_id_happen`,`sys_msg_id_stop`,`sys_msg_id_fail`,`can_cast_with_invis`,`ignores_counter_magic`,`is_buff`,`impl`) VALUES ('10000','禁言','0','0','0','0','0','0','0','0','none','0','0.0','0','0','0','0','-1','0','128','0','0','0','0','0','禁言','0','0','-1','0','0','0','0','0','0',NULL);