-- 合併表：etc_items / armors / weapons 已合併於此，服務器僅讀取本表。
CREATE TABLE `items` (
  `item_id` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(45) NOT NULL DEFAULT '',
  `type` varchar(10) NOT NULL DEFAULT 'none',
  `dmg_small` int(10) NOT NULL DEFAULT '0',
  `dmg_large` int(10) NOT NULL DEFAULT '0',
  `material` varchar(30) NOT NULL DEFAULT '',
  `weight` int(10) NOT NULL DEFAULT '0',
  `inv_gfx_id` int(10) NOT NULL DEFAULT '0',
  `grd_gfx_id` int(10) NOT NULL DEFAULT '0',
  `nameid` varchar(40) NOT NULL DEFAULT '$0',
  `sell` int(10) NOT NULL DEFAULT '0',
  `piles` int(10) NOT NULL DEFAULT '0',
  `trade` int(10) NOT NULL DEFAULT '0',
  `drop` int(10) NOT NULL DEFAULT '0',
  `werehouse` int(10) NOT NULL DEFAULT '0',
  `enchant` int(10) NOT NULL DEFAULT '0',
  `safe_enchant` int(10) NOT NULL DEFAULT '0',
  `royal` int(10) NOT NULL DEFAULT '0',
  `knight` int(10) NOT NULL DEFAULT '0',
  `elf` int(10) NOT NULL DEFAULT '0',
  `mage` int(10) NOT NULL DEFAULT '0',
  `add_hit` int(10) NOT NULL DEFAULT '0',
  `add_dmg` int(10) NOT NULL DEFAULT '0',
  `add_ac` int(10) NOT NULL DEFAULT '0',
  `add_str` int(10) NOT NULL DEFAULT '0',
  `add_dex` int(10) NOT NULL DEFAULT '0',
  `add_con` int(10) NOT NULL DEFAULT '0',
  `add_int` int(10) NOT NULL DEFAULT '0',
  `add_wis` int(10) NOT NULL DEFAULT '0',
  `add_cha` int(10) NOT NULL DEFAULT '0',
  `add_hp` int(10) NOT NULL DEFAULT '0',
  `add_mp` int(10) NOT NULL DEFAULT '0',
  `add_hpr` int(10) NOT NULL DEFAULT '0',
  `add_mpr` int(10) NOT NULL DEFAULT '0',
  `add_sp` int(10) NOT NULL DEFAULT '0',
  `add_mr` int(10) NOT NULL DEFAULT '0',
  `haste` int(10) NOT NULL DEFAULT '0',
  `can_be_dmg` int(10) NOT NULL DEFAULT '0',
  `minlvl` int(10) NOT NULL DEFAULT '0',
  `maxlvl` int(10) unsigned NOT NULL DEFAULT '0',
  `effect_id` int(10) NOT NULL DEFAULT '0',
  `skill_id` int(10) NOT NULL DEFAULT '0',
  `two_hand` int(10) NOT NULL DEFAULT '0',
  `set_item_uid` int(10) NOT NULL DEFAULT '0',
  `continuous` int(10) NOT NULL DEFAULT '0',
  `use_type` varchar(255) NOT NULL DEFAULT 'none',
  `item_desc_id` int(10) unsigned NOT NULL DEFAULT '0',
  `stackable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `charge_count` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `loc_x` int(10) unsigned NOT NULL DEFAULT '0',
  `loc_y` int(10) unsigned NOT NULL DEFAULT '0',
  `map_id` int(10) unsigned NOT NULL DEFAULT '0',
  `bless` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `tradable` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `deletable` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sealable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `delay_id` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `delay_time` int(10) unsigned NOT NULL DEFAULT '0',
  `delay_effect` int(10) unsigned NOT NULL DEFAULT '0',
  `food_volume` int(10) unsigned NOT NULL DEFAULT '0',
  `save_at_once` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `charge_time` int(10) unsigned NOT NULL DEFAULT '0',
  `expiration_time` varchar(255) DEFAULT NULL,
  `grade` tinyint(1) NOT NULL DEFAULT '-1',
  `range` tinyint(3) NOT NULL DEFAULT '0',
  `hit_modifier` tinyint(3) NOT NULL DEFAULT '0',
  `dmg_modifier` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`),
  KEY `uid` (`item_id`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='items (merged)';
